### ISSUE TITLE
bug mitogen version 0.3.4 with running ansible 2.15 or 2.16

### ISSUE THREAD

**Issue by mehdia4ever** [mitogen-hq/mitogen#1039] opened 2024-02-16 16:07 UTC
Please drag-drop large logs as text file attachments.

When i execute any playbook with mitogen 0.3.4 version, a have this issue:

**ERROR! Your Ansible version ((2, 15, 7)) is too recent. The most recent version
supported by Mitogen for Ansible is (2, 13).x. Please check the Mitogen
release notes to see if a new version is available, otherwise
subscribe to the corresponding GitHub issue to be notified when
support becomes available.**

* Which version of Ansible are you running?
* ansible-core 2.15.7
* Is your version of Ansible patched in any way?
* no
* Are you running with any custom modules, or `module_utils` loaded?
* no
*

**Comment by moreati** [comment] 2024-02-22 10:32
duplicate of #1021

**Closed by moreati** 2024-02-22 10:32 UTC
Labels: bug, affects-0.3
